# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V7GZDemNMDHtrMJGnE7ltXDMYWOQ5gWq
"""

import pandas as pd
from sklearn.ensemble import RandomForestClassifier
import joblib

# Create a dummy DataFrame for student_data for demonstration purposes
student_data = pd.DataFrame({
    'attendance': [80, 90, 70, 95, 60, 85, 75, 92, 68, 88],
    'CAT': [60, 70, 50, 80, 45, 65, 55, 75, 40, 72],
    'exam': [70, 80, 60, 85, 50, 72, 65, 88, 48, 78],
    'dropout': ['No', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No']
})

# Assuming student_data is a pandas DataFrame, save it to CSV
student_data.to_csv("student_sample.csv", index=False)

# Load the exported dataset (ensure this file path is correct if different from the saved one)
data = pd.read_csv("student_sample.csv") # Changed from student_data.csv to student_sample.csv

# Features and target
X = data[["attendance", "CAT", "exam"]]
y = data["dropout"]

# If your target is categorical (Yes/No), convert to 0/1
if y.dtype == 'object':
    y = y.map({"No": 0, "Yes": 1})

# Train Random Forest
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X, y)

# Save the model
joblib.dump(model, "student_model.pkl")

print("Model trained and saved successfully!")

# Commented out IPython magic to ensure Python compatibility.
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
 
# Load the trained model
model = joblib.load("student_model.pkl")
st.title("Student Dropout Prediction")
 
# Input sliders
attendance = st.slider("Attendance %", 0, 100, 80)
cat_score = st.slider("CAT Score", 0, 100, 65)
exam_score = st.slider("Exam Score", 0, 100, 70)
 
# Prepare input for prediction
input_data = pd.DataFrame({
     "attendance": [attendance],
     "CAT": [cat_score],
     "exam": [exam_score]
})
 
# Predict button
if st.button("Predict"):
     prediction = model.predict(input_data)[0]
     proba = model.predict_proba(input_data)[0]
 
     st.subheader(f"Prediction: {'Dropout' if prediction == 1 else 'No Dropout'}")
     st.write(f"Probability of dropout: {proba[1]*100:.2f}%")
    
# Bar chart of inputs
     fig, ax = plt.subplots()
     sns.barplot(x=input_data.columns, y=input_data.loc[0], palette="viridis", ax=ax)
     ax.set_ylim(0, 100)
     ax.set_title("Student Metrics")
     st.pyplot(fig)
 
# Scatter plot: CAT vs Exam
     fig2, ax2 = plt.subplots()
     ax2.scatter(input_data["CAT"], input_data["exam"], color='blue', s=100)
     ax2.set_xlim(0, 100)
     ax2.set_ylim(0, 100)
     ax2.set_xlabel("CAT Score")
     ax2.set_ylabel("Exam Score")
     ax2.set_title("CAT vs Exam Score")
     st.pyplot(fig2)
